<!--CONTENT ENDS-->

<address>Maintained by webmaster@wpi.edu<br />
Last modified: <!--#config timefmt="%b %d, %Y, %H:%M %Z"--><!--#echo var="LAST_MODIFIED"--></address>

<div id="footernav">
<a href="/"><img src="/Buttons/seal.gif" alt="[WPI]" title="WPI Homepage" width="70" height="32"></a>
<a href="/academics/Depts/Math/"><img alt="[Math]" src="/Academics/Depts/Math/CIMS/Images/math.gif" width="50" height="32"></a>
<!--#if expr="$homepage != y" --><a href="/academics/Depts/Math/CIMS/"><img src="/Buttons/home.gif" alt="[Home]" width="50" height="32"></a><!--#endif -->
<!--#if expr="$toc" --><a href="<!--#echo var="toc" -->"><img src="/Buttons/toc.gif" alt="[Contents]" width="77" height="32"></a><!--#endif -->
<!--#if expr="$back" --><a href="<!--#echo var="back" -->"><img src="/Buttons/back.gif" alt="[Back]" width="50" height="32"></a><!--#endif -->
<!--#if expr="$forward" --><a href="<!--#echo var="forward" -->"><img src="/Buttons/forward.gif" alt="[Forward]" width="77" height="32"></a><!--#endif -->
<!--#if expr="$top = y" --><a href="#top"><img src="/Buttons/top.gif" alt="[Top]" width="50" height="32"></a><!--#endif -->
</div>

<p class="footer">Department of Mathematical Sciences - 
Worcester Polytechnic Institute<br /> 100 Institute Road, Worcester, MA 01609-2280<br />
Phone: +1-508-831-5241 - Fax: +1-508-831-5824 - 
<a href="mailto:ma-questions@wpi.edu">ma-questions@wpi.edu</a></p>

</div>

</body></html>