<ul>

<!--#if expr="$REQUEST_URI = /" -->
<li id="first"><a href="/academics/math/CIMS/">CIMS  Home</a></li>
<!--#else -->
<li><a href="/academics/math/CIMS/">CIMS Home</a></li>
<!--#endif -->

<!--#if expr="$REQUEST_URI = /About/" -->
<li class="downsub"><a href="/academics/math/CIMS/About/">About CIMS</a>
<ul>
	<li><a href="/academics/math/CIMS/About/mission.html">Mission</a></li>
	<li><a href="/academics/math/CIMS/About/benefits.html">Benefits</a></li>
	<li><a href="/academics/math/CIMS/About/members.html">Members</a></li>
	<li><a href="/academics/math/CIMS/About/advboard.html">Advisory Board</a></li>
</ul></li>
<!--#else -->
<li><a href="/academics/math/CIMS/About/">About CIMS</a></li>
<!--#endif -->

<!--#if expr="$REQUEST_URI = /IndSpon/" -->
<li class="downsub"><a href="/academics/math/CIMS/IndSpon/">Project Sponsors</a>
<ul>
	<li><a href="/academics/math/CIMS/IndSpon/Sponsor/index.html">Sponsoring a Project</a></li>
</ul></li>
<!--#else -->
<li><a href="/academics/math/CIMS/IndSpon/">Project Sponsors</a></li>
<!--#endif -->

<!--#if expr="$REQUEST_URI = /IndProj/" -->
<li class="downsub"><a href="/academics/math/CIMS/IndProj/">Industrial Projects</a>
<ul>
	<li><a href="/academics/math/CIMS/IndProj/Projects/">Project List</a></li>
</ul></li>
<!--#else -->
<li><a href="/academics/math/CIMS/IndProj/">Industrial Projects</a></li>
<!--#endif -->

<!--#if expr="$REQUEST_URI = /REU/" -->
<li class="downsub"><a href="/academics/math/CIMS/REU/">REU Program</a>
<ul>
	<!--#if expr="$REQUEST_URI = /Current/" -->
	<li><a href="/academics/math/CIMS/REU/Current/">About REU 2014</a>
	<ul>
		<li><a href="/academics/math/CIMS/REU/Current/geninfo.html">Information</a></li>
	</ul></li>
	<!--#else -->
	<li><a href="/academics/math/CIMS/REU/Current/index.html">About REU 2014</a></li>
	<!--#endif-->
	<li><a href="/academics/math/CIMS/REU/students.html">Students</a></li>
	<li><a href="/academics/math/CIMS/REU/projects.html">Projects</a></li>
	<li><a href="/academics/math/CIMS/REU/alumni.html">Alumni Highlights</a></li>
</ul></li>
<!--#else -->
<li><a href="/academics/math/CIMS/REU/">REU Program</a></li>
<!--#endif -->

<!--#if expr="$REQUEST_URI = /PICMath/" -->
<li class="down"><a href="/academics/math/CIMS/PICMath/">The PIC Math Program</a></li>
<!--#else -->
<li><a href="/academics/math/CIMS/PICMath/">The PIC Math Program</a></li>
<!--#endif -->

<!--#if expr="$REQUEST_URI = /Teachers/" -->
<li class="downsub"><a href="/academics/math/CIMS/Teachers/">Mathematics in Industry Institute for Teachers 2000-2005</a>
<ul>
	<li><a href="/academics/math/CIMS/Teachers/about.html">About</a></li>
	<li><a href="/academics/math/CIMS/Teachers/committee.html">Organizing Committee</a></li>
	<li><a href="/academics/math/CIMS/Teachers/workshops.html">Workshops</a></li>
</ul></li>
<!--#else -->
<li><a href="/academics/math/CIMS/Teachers/">Mathematics in Industry Institute for Teachers 2000-2005</a></li>
<!--#endif -->

<!--#if expr="$REQUEST_URI = /IMPHSS/" -->
<li class="down"><a href="/academics/math/CIMS/IMPHSS/">Industrial Math Projects for High School </a></li>
<!--#else -->
<li><a href="/academics/math/CIMS/IMPHSS/">Industrial Math Projects for High School</a></li>
<!--#endif -->

<!--#if expr="$REQUEST_URI = /MPI/" -->
<li class="down"><a href="/academics/math/CIMS/MPI/">Mathematical Problems in Industry</a></li>
<!--#else -->
<li><a href="/academics/math/CIMS/MPI/">Mathematical Problems in Industry</a></li>
<!--#endif -->

<!--#if expr="$REQUEST_URI = /mpe2013/" -->
<li class="down"><a href="/academics/math/CIMS/mpe2013/">Mathematics of Planet Earth </a></li>
<!--#else -->
<li><a href="/academics/math/CIMS/mpe2013/">Mathematics of Planet Earth 2013</a></li>
<!--#endif -->

<!--#if expr="$REQUEST_URI = /IMMG/" -->
<li class="downsub"><a href="/academics/math/CIMS/IMMG/">Industrial Microwave Modeling Group</a>
<ul>
	<li><a href="/academics/math/CIMS/IMMG/Objectives/">Objectives</a></li>
	<li><a href="/academics/math/CIMS/IMMG/Research/">Research</a></li>
	<li><a href="/academics/math/CIMS/IMMG/Activities/">Activities</a></li>
	<li><a href="/academics/math/CIMS/IMMG/Publications/">Publications</a></li>
	<!--#if expr="$REQUEST_URI = /Seminars/" -->
	<li><a href="/academics/math/CIMS/IMMG/Seminars/">Seminars</a>
	<ul>
		<!--#if expr="$REQUEST_URI = /Current/" -->
		<li><a href="/academics/math/CIMS/IMMG/Seminars/Current/">Seminar 16</a>
		<ul>
			<li><a href="/academics/math/CIMS/IMMG/Seminars/Current/abstract.html">Submit Abstract</a></li>
			<li><a href="/academics/math/CIMS/IMMG/Seminars/Current/location.html">Location & Directions</a></li>
			<li><a href="/academics/math/CIMS/IMMG/Seminars/Current/contest.html">Student Contest</a></li>
		<!--
			<li><a href="/academics/math/CIMS/IMMG/Seminars/Current/register.html">Registration</a></li>
			<li><a href="/academics/math/CIMS/IMMG/Seminars/Current/abstract.html">Submit Abstract</a></li>
			<li><a href="/academics/math/CIMS/IMMG/Seminars/Current/papers.html">Submit Paper</a></li>
			<li><a href="/academics/math/CIMS/IMMG/Seminars/Current/location.html">Location & Directions</a></li>
			<li><a href="/academics/math/CIMS/IMMG/Seminars/Current/accommodations.html">Accommodations</a></li>
			<li><a href="/academics/math/CIMS/IMMG/Seminars/Current/contest.html">Student Contest</a></li>
			<li><a href="/academics/math/CIMS/IMMG/Seminars/Current/program.html">Program</a></li>
			<li><a href="/academics/math/CIMS/IMMG/Seminars/Current/banquet.html">Banquet</a></li>
		
			<li><a href="/academics/math/CIMS/IMMG/Seminars/Current/course.html">Short Course</a></li>
			<li><a href="/academics/math/CIMS/IMMG/Seminars/Current/excursion.html">Excursion to Eckart</a></li>
			<li><a href="/academics/math/CIMS/IMMG/Seminars/Current/photos.html">Photo Gallery</a></li>
		-->
		</ul>
		</li>
		<!--#else -->
		<li><a href="/academics/math/CIMS/IMMG/Seminars/Current/">Seminar 16</a></li>
		<!--#endif -->
		<li><a href="/academics/math/CIMS/IMMG/Seminars/Past/">Past Seminars</a></li>
	</ul></li>
	<!--#else -->
	<li><a href="/academics/math/CIMS/IMMG/Seminars/Current/">Seminars</a></li>
	<!--#endif -->
	<li><a href="/academics/math/CIMS/IMMG/Partnership/">Partnership</a></li>
</ul></li>
<!--#else -->
<li><a href="/academics/math/CIMS/IMMG/">Industrial Microwave Modeling Group</a></li>
<!--#endif -->

<!--#if expr="$REQUEST_URI = /Events/" -->
<li class="down"><a href="/academics/math/CIMS/Events/">Events</a></li>
<!--#else -->
<li><a href="/academics/math/CIMS/Events/">Events</a></li>
<!--#endif -->

<li class="search"><span>Search</span> 
<form method="GET" action="/cgi-bin/search.pl"><div> 
<input type="hidden" name="dept" value="math" id="math"> 
<input name="search_query" type="text" size="15"> 
<input type="image" src="/Buttons/go.gif" alt="Go" value="Go"></div></form></li> 
<li class="related"><span>Related Sites</span> 
<ul> 
	<li><a href="/academics/Depts/Math/">Department of Mathematical Sciences</a></li> 
	<li><a href="/">WPI Homepage</a></li> 

</ul>
</li>
</ul>