<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
        "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=iso-8859-1">

<!--#if expr="$redirect"--><!--#if expr="$redirectURL"-->
<meta http-equiv="Refresh" content="<!--#echo var="redirect"-->;url=<!--#echo var="redirectURL"-->">
<!--#endif--><!--#endif-->

<title>CIMS
<!--#if expr="$title"--> - <!--#echo var="title"--><!--#endif-->
<!--#if expr="$subtitle"--> - <!--#echo var="subtitle"--><!--#endif-->
</title>

<!--#if expr="$description" --><meta name="Description" content="<!--#echo var="description" -->"><!--#endif -->
<!--#if expr="$keywords" --><meta name="Keywords" content="<!--#echo var="keywords" -->"><!--#endif -->

<!--#include virtual="/css.inc"-->
<link rel="Stylesheet" media="all" type="text/css" href="/Templates/buttonsthin.css">
<link rel="Stylesheet" media="all" type="text/css" href="/academics/Depts/Math/CIMS/cims.css">


</head>
<body>

<div id="header"><div id="wpihome"><a href="/"><img src="/Images/logohome39c.gif" width="171" height="66" title="WPI Homepage" alt="Worcester Polytechnic Institute (WPI)"></a></div></div>

<div id="endcap"><img src="/Images/spacer.gif" width="1" height="1" alt=""></div>

<div class="replace" id="banner"><a href="/academics/Depts/Math/CIMS/" name="top"><em></em>CIMS</a></div>

<div id="nav">
<div class="menutop"><img src="/Images/spacer.gif" width="1" height="1" alt=""></div>
<!--#include virtual="menu.inc"-->
</div>

<div id="content">
<a name="content" tabindex="1"></a>

<h1><!--#if expr="$title"--><!--#echo var="title"--><!--#endif--><!--#if expr="$subtitle"--> - <!--#echo var="subtitle"--><!--#endif--></h1>
<!--CONTENT BEGINS-->