<ul>

<!--#if expr="$REQUEST_URI = /" -->
<li id="first"><a href="/academics/Depts/Math/CIMS/">CIMS Home</a></li>
<!--#else -->
<li><a href="/academics/Depts/Math/CIMS/">CIMS Home</a></li>
<!--#endif -->

<!--#if expr="$REQUEST_URI = /About/" -->
<li class="downsub"><a href="/academics/Depts/Math/CIMS/About/">About CIMS</a>
<ul>
	<li><a href="/academics/Depts/Math/CIMS/About/mission.html">Mission</a></li>
	<li><a href="/academics/Depts/Math/CIMS/About/benefits.html">Benefits</a></li>
	<li><a href="/academics/Depts/Math/CIMS/About/members.html">Members</a></li>
	<li><a href="/academics/Depts/Math/CIMS/About/advboard.html">Advisory Board</a></li>
</ul></li>
<!--#else -->
<li><a href="/academics/Depts/Math/CIMS/About/">About CIMS</a></li>
<!--#endif -->

<!--#if expr="$REQUEST_URI = /IndSpon/" -->
<li class="downsub"><a href="/academics/Depts/Math/CIMS/IndSpon/">Project Sponsors</a>
<ul>
	<li><a href="/academics/Depts/Math/CIMS/IndSpon/Sponsor/index.html">Sponsoring a Project</a></li>
</ul></li>
<!--#else -->
<li><a href="/academics/Depts/Math/CIMS/IndSpon/">Project Sponsors</a></li>
<!--#endif -->

<!--#if expr="$REQUEST_URI = /IndProj/" -->
<li class="downsub"><a href="/academics/Depts/Math/CIMS/IndProj/">Industrial Projects</a>
<ul>
	<li><a href="/academics/Depts/Math/CIMS/IndProj/Projects/">Project List</a></li>
</ul></li>
<!--#else -->
<li><a href="/academics/Depts/Math/CIMS/IndProj/">Industrial Projects</a></li>
<!--#endif -->

<!--#if expr="$REQUEST_URI = /REU/" -->
<li class="downsub"><a href="/academics/Depts/Math/CIMS/REU/">REU Program</a>
<ul>
	<!--#if expr="$REQUEST_URI = /Current/" -->
	<li><a href="/academics/Depts/Math/CIMS/REU/Current/">About REU 2011</a>
	<ul>
		<li><a href="/academics/Depts/Math/CIMS/REU/Current/geninfo.html">Information</a></li>
	</ul></li>
	<!--#else -->
	<li><a href="/academics/Depts/Math/CIMS/REU/Current/index.html">About REU 2011</a></li>
	<!--#endif-->
	<li><a href="/academics/Depts/Math/CIMS/REU/students.html">Students</a></li>
	<li><a href="/academics/Depts/Math/CIMS/REU/projects.html">Projects</a></li>
	<li><a href="/academics/Depts/Math/CIMS/REU/alumni.html">Alumni</a></li>
</ul></li>
<!--#else -->
<li><a href="/academics/Depts/Math/CIMS/REU/">REU Program</a></li>
<!--#endif -->

<!--#if expr="$REQUEST_URI = /Teachers/" -->
<li class="downsub"><a href="/academics/Depts/Math/CIMS/Teachers/">High School Teachers</a>
<ul>
	<li><a href="/academics/Depts/Math/CIMS/Teachers/about.html">About</a></li>
	<li><a href="/academics/Depts/Math/CIMS/Teachers/committee.html">Organizing Committee</a></li>
	<li><a href="/academics/Depts/Math/CIMS/IMPHSS/">Student Projects</a></li>
	<li><a href="/academics/Depts/Math/CIMS/Teachers/workshops.html">Workshops</a></li>
</ul></li>
<!--#else -->
<li><a href="/academics/Depts/Math/CIMS/Teachers/">High School Teachers</a></li>
<!--#endif -->

<!--#if expr="$REQUEST_URI = /MPI/" -->
<li class="down"><a href="/academics/Depts/Math/CIMS/MPI/">Mathematical Problems in Industry</a></li>
<!--#else -->
<li><a href="/academics/Depts/Math/CIMS/MPI/">Mathematical Problems in Industry</a></li>
<!--#endif -->

<!--#if expr="$REQUEST_URI = /IMMG/" -->
<li class="downsub"><a href="/academics/Depts/Math/CIMS/IMMG/">IMMG</a>
<ul>
	<li><a href="/academics/Depts/Math/CIMS/IMMG/Objectives/">Objectives</a></li>
	<li><a href="/academics/Depts/Math/CIMS/IMMG/Research/">Research</a></li>
	<li><a href="/academics/Depts/Math/CIMS/IMMG/Activities/">Activities</a></li>
	<li><a href="/academics/Depts/Math/CIMS/IMMG/Publications/">Publications</a></li>
	<!--#if expr="$REQUEST_URI = /Seminars/" -->
	<li><a href="/academics/Depts/Math/CIMS/IMMG/Seminars/Current">Seminars</a>
	<ul>
		<li><a href="/academics/Depts/Math/CIMS/IMMG/Seminars/Current/register.html">Registration</a></li>
		<li><a href="/academics/Depts/Math/CIMS/IMMG/Seminars/Current/submitAbstract.html">Submit Abstract</a></li>
		<li><a href="/academics/Depts/Math/CIMS/IMMG/Seminars/Current/submitPaper.html">Submit Paper</a></li>
		<li><a href="/academics/Depts/Math/CIMS/IMMG/Seminars/Current/programglance.html">Program at a Grance</a></li>
		<li><a href="/academics/Depts/Math/CIMS/IMMG/Seminars/Current/program.html">Full Program</a></li>
		<li><a href="/academics/Depts/Math/CIMS/IMMG/Seminars/Current/locationAndDirections.html">Location & Directions</a></li>
		<li><a href="/academics/Depts/Math/CIMS/IMMG/Seminars/Current/accommodations.html">Accommodations</a></li>
		<li><a href="/academics/Depts/Math/CIMS/IMMG/Seminars/Current/sls.html">Trip to SLS2</a></li>
		<li><a href="/academics/Depts/Math/CIMS/IMMG/Seminars/Current/dinner.html">Seminar Banquet</a></li>
	</ul>
	</li>
	<!--#else -->
	<li><a href="/academics/Depts/Math/CIMS/IMMG/Seminars/Current">Seminars</a></li>
	<!--#endif -->

	<!--#if expr="$REQUEST_URI = /Archive/" -->
	<li><a href="/academics/Depts/Math/CIMS/IMMG/Archive">Past Seminars</a>
	<ul>
		<!--#if expr="$REQUEST_URI = /Seminar13/" -->
		<li><a href="/academics/Depts/Math/CIMS/IMMG/Archive/Seminar13">Seminar 13</a>
		<ul>
			<li><a href="/academics/Depts/Math/CIMS/IMMG/Archive/Seminar13/program.html">Program</a></li>
			<li><a href="/academics/Depts/Math/CIMS/IMMG/Archive/Seminar13/photos.html">Photos</a></li>
		</ul>
		</li>
		<!--#else -->
		<li><a href="/academics/Depts/Math/CIMS/IMMG/Archive/Seminar13">Seminar 13</a></li>
		<!--#endif -->
		<!--#if expr="$REQUEST_URI = /Seminar12/" -->
		<li><a href="/academics/Depts/Math/CIMS/IMMG/Archive/Seminar12">Seminar 12</a>
		<ul>
			<li><a href="/academics/Depts/Math/CIMS/IMMG/Archive/Seminar12/program.html">Program</a></li>
			<li><a href="/academics/Depts/Math/CIMS/IMMG/Archive/Seminar12/photos.html">Photos</a></li>
		</ul>
		</li>
		<!--#else -->
		<li><a href="/academics/Depts/Math/CIMS/IMMG/Archive/Seminar12">Seminar 12</a></li>
		<!--#endif -->
	</ul>
	</li>
	<!--#else-->
	<li><a href="/academics/Depts/Math/CIMS/IMMG/Archive">Past Seminars</a></li>
	<!--#endif -->
	<li><a href="/academics/Depts/Math/CIMS/IMMG/Partnership/">Partnership</a></li>
</ul></li>
<!--#else -->
<li><a href="/academics/Depts/Math/CIMS/IMMG/">IMMG</a></li>
<!--#endif -->

<!--#if expr="$REQUEST_URI = /Events/" -->
<li class="down"><a href="/academics/Depts/Math/CIMS/Events/">Events</a></li>
<!--#else -->
<li><a href="/academics/Depts/Math/CIMS/Events/">Events</a></li>
<!--#endif -->

<!--#if expr="$REQUEST_URI = /WPI/" -->
<li class="down"><a href="/academics/Depts/Math/CIMS/WPI/">About WPI</a></li>
<!--#else -->
<li><a href="/academics/Depts/Math/CIMS/WPI/">About WPI</a></li>
<!--#endif -->

<li class="search"><span>Search</span> 
<form method="GET" action="/cgi-bin/search.pl"><div> 
<input type="hidden" name="dept" value="math" id="math"> 
<input name="search_query" type="text" size="15"> 
<input type="image" src="/Buttons/go.gif" alt="Go" value="Go"></div></form></li> 
<li class="related"><span>Related Sites</span> 
<ul> 
	<li><a href="/academics/Depts/Math/">Department of Mathematical Sciences</a></li> 
	<li><a href="/">WPI Homepage</a></li> 

</ul>
</li>
</ul>
